### ISSUE TITLE
Linter does not cover ASCIIdoc files

### ISSUE THREAD

**Issue by ericherman** [diggsweden/open-source-project-template#13]
### Contact Details

eric@publiccode.net

### What happened?

Several files are `.adoc`, however these files are not covered by the linter

### Steps To Reproduce

Look at the MegaLinter config.

### What did you expect?

I expected all docs to be covered.

**Comment by janderssonse** [comment]
Had a brief look around, I guess we will have to wait for a real solution to this one, as the AsciiDoc-people are busy finishing their specification, and only then it will be possible to create a real linter it is a long featured request. https://github.com/asciidoctor/asciidoctor-extensions-lab/issues/6.

However the author of asciidoc in the same mentions vale as a half-measure (it will lint the html-output of asciidoc) https://github.com/vshn/vale. And combining that with the proposal here, (just run asciidoctor in the docs https://stackoverflow.com/questions/73556861/basic-asciidoc-linter) I think we would get as good a linting we can get currently.. That is, if that take works satisfactory.

**Comment by ericherman** [comment]
Use a "half-measure" as an incremental step is still progress. I recommend adding something about the trajectory of it on the roadmap.

**Comment by janderssonse** [comment]
Not relevant any longer, as we just went for markdown. This was done mainly because of GitHub's non optimal support for adoc. Closing.
