### ISSUE TITLE
Some files have trailing whitespace on lines

### ISSUE THREAD

**Issue by ericherman** [diggsweden/open-source-project-template#14]
### Contact Details

eric@publiccode.net

### What happened?

When editing a file, I noticed some lines had trailing whitespaces.

### Steps To Reproduce

```
grep -l '\s\+$' \
	$(git ls-tree --full-tree -r --name-only HEAD) \
	| grep -v '\.png' \
```

### What did you expect?

I expected that the linters would be configured to flag trailing whitespaces are errors for Markdown and ASCIIdoc files.

**Comment by janderssonse** [comment]
Good find! I also expected the MarkdownLinter to find the MD ones.. but not... Had a closer look and found that the default ruleset used (in megalinter) for this ruleset i quite sparse, and does not seem to include much rules. https://github.com/oxsecurity/megalinter/blob/main/TEMPLATES/.markdownlint.json. Will play around with custom one, with added conf.
